---

- name: Add Bridge Domain
  aci_bd:
    host: "{{ apic }}"
    password: "{{ creds }}"
    validate_certs: no
    state: present
    tenant: "{{ TN }}"
    bd: "{{ item }}"
    vrf: "{{ VRF }}"
  loop: "{{ BD }}"