---

- name: Create a Snapshot
  aci_config_snapshot:
    host: "{{ apic }}"
    password: "{{ creds }}"
    validate_certs: no
    state: present
    export_policy: Ansible-Config
    max_count: 10
    description: execute before playbook