---

- name: Delete Tenant "{{ TN }}"
  aci_tenant:
    host: "{{ apic }}"
    password: "{{ pw }}"
    validate_certs: no
    tenant: "{{ TN }}"
    description: tenant created by ansible
    state: absent