---

- name: Create an EPG
  aci_epg:
        hostname: "{{ apic }}"
        password: "{{ pw }}"
        validate_certs: no
        tenant: "{{ TN }}"
        ap: "{{ AP }}_app"
        epg: "{{ EPG }}"
        bd: "{{ BD }}"
        state: present