---

- name: Create an EPG
  aci_epg:
    hostname: "{{ apic }}"
    password: "{{ pw }}"
    validate_certs: no
    tenant: "{{ TN }}"
    ap: "{{ AP }}-app"
    epg: "{{ item.0 }}"
    bd: "{{ item.1 }}"
    state: present
  with_together:
    - "{{ EPG }}"
    - "{{ BD }}"